### ISSUE TITLE
Crashed when loading on Dedicated Server

### ISSUE THREAD

**Issue by Darkmega18** [mcpecommander/Mobultion-mod#1]
[crash-2018-02-08_03.01.59-server.txt](https://github.com/mcpecommander/Mobultion-mod/files/1706176/crash-2018-02-08_03.01.59-server.txt)

Heres the crash, uploaded for you.

**Comment by mcpecommander** [comment]
I solved it, It was a dump fast mistake. I will release an update on Sunday 11/February/2018.

**Comment by Darkmega18** [comment]
Roger. thanks.
