### ISSUE TITLE
Angel spider crash

### ISSUE THREAD

**Issue by mxnmnm** [mcpecommander/Mobultion-mod#10]
https://pastebin.com/DPw579T5

forge 1.12.2-14.23.4.27055

mobultion-0.4.1

I didn't realize there was an update and I don't know how to recreate the crash.  Also how can I disable a mob in the config?  Would just removing all of the biomes in the mob spawn part of the config be enough?

**Comment by mcpecommander** [comment]
There is no longer a way to disable a mob in the configs but as you said you can use the spawn changer stick (creative only item) and left click any mob you want and you can take away the spawn biomes causing the mob to never spawn (this does not require any restart to the world or the game).
The bug however is a null pointer that I forgot to fix.
An update will be released shortly.
