### ISSUE TITLE
Crash on Server

### ISSUE THREAD

**Issue by Darkmega18** [mcpecommander/Mobultion-mod#12]
MC 1.12.2
forge 1.12.2 2705
mobultion 0.4.3

Mod crashes the server unfortunately. :V 
[crash-2018-07-05_03.34.28-server.txt](https://github.com/mcpecommander/Mobultion-mod/files/2165446/crash-2018-07-05_03.34.28-server.txt)

**Comment by mcpecommander** [comment]
Are you sure it was my mod and if so, can you please check if that is the whole crash log. it seems that it is missing some parts

**Comment by mcpecommander** [comment]
You know what, It was my mod, sorry for that. A new hot fix will be released shortly

**Comment by Darkmega18** [comment]
RIP! alrighty, thanks. :)
