### ISSUE TITLE
Angel spider crash 2.0

### ISSUE THREAD

**Issue by mxnmnm** [mcpecommander/Mobultion-mod#15]
https://pastebin.com/1L0iCns9

forge 1.12.2-14.23.4.27055

mobultion-0.4.5

Yea like the changelog says you didn't actually fix it xD the maybe has become no.  Good thing I have biometweaker to just remove all angel spider spawns until they're 100% fixed

**Comment by mcpecommander** [comment]
Did you have the mod installed before creating the world or after creating your world??

**Comment by mxnmnm** [comment]
I disabled all of their spawns until I updated, as for when I created the world I'm 75% sure it was after the update.  But I had the mod installed the entire time.  I might've enabled the angel spiders after creating the world tho but I'm not sure.

**Comment by mcpecommander** [comment]
The animation api that the mod depends on quite a lot is having major issues and has not been updated for a while now (8 months and going), so I have been drifting away from the modding scene so it might be a good idea to disable the mod for now. I do not want to fix a mod that is bound to break right away.

**Comment by mxnmnm** [comment]
Well no need for me to disable the entire mod because I can just use other mods and/or the configs (removing all of the biomes in the config stops it from spawning) and using biometweaker just in case seems to work fine!

(ok nvm it didn't especially after more research it seems to be when two animations are trying to happen at the same time or something like that, good thing it's somewhat rare for most mobs)

**Comment by mxnmnm** [comment]
I hope the lack of updates on the api doesn't stop future updates :(

**Comment by mcpecommander** [comment]
This mod no longer supports any version than 1.16.5 so I am sorry but no bug fixing, just rewrites.
