### ISSUE TITLE
Player getting kicked due to CME in Craftstudio

### ISSUE THREAD

**Issue by LemADEC** [mcpecommander/Mobultion-mod#16]
see https://github.com/Leviathan-Studio/CraftStudioAPI/issues/39

**Comment by mcpecommander** [comment]
I do not know if you noticed, but craftstudio has not updated since last year. I can not fix what they won't fix themselves. My mod's major updates has been on hold for the last 4 months because of that.

**Comment by LemADEC** [comment]
I've fixed that issue, what else is game breaking the API?

**Comment by Darkmega18** [comment]
got hit by this tonight as well during some combat testing.

https://github.com/Leviathan-Studio/CraftStudioAPI/issues/39#issuecomment-418152749

**Comment by mcpecommander** [comment]
This mod no longer supports any version than 1.16.5 so I am sorry but no bug fixing, just rewrites.
