### ISSUE TITLE
Spider egg spawning spiders inside walls

### ISSUE THREAD

**Issue by LemADEC** [mcpecommander/Mobultion-mod#19]
As of 0.4.5, we frequently see stacks of strings around spider eggs inside caves.
While in Spectator mode, we can spiders spawning inside the walls, right at the limit of air, and then dying from suffocation.

**Comment by mcpecommander** [comment]
I know of that problem but I do not have time to fix it any time soon (at least a month or two).

**Comment by mcpecommander** [comment]
This mod no longer supports any version than 1.16.5 so I am sorry but no bug fixing, just rewrites.
