### ISSUE TITLE
I don't exactly know what is causing this issue, but I hope you can fix it soon! 

### ISSUE THREAD

**Issue by ThisJustInLocal** [mcpecommander/Mobultion-mod#6]
I'm not a coder, but here is all I can offer. It may have to do with the MMSR (Much More Spiders Reborn) mod which adds a spider by the same name. If it has to do with the ID, perhaps changing the name to something like magmaspider or lava_spider may fix it.

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Duplicate stat id: "TranslatableComponent{key='stat.entityKill', args=[TranslatableComponent{key='entity.magma_spider.name', args=[], siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}" and "TranslatableComponent{key='stat.entityKill', args=[TranslatableComponent{key='entity.magma_spider.name', args=[], siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}" at id stat.killEntity.magma_spider

**Comment by mcpecommander** [comment]
I will release an update adding my mod id to the name but that will have to wait until mid-April. Sorry.

**Comment by mcpecommander** [comment]
Fixed in 0.3 released on Sunday 22/4
