### ISSUE TITLE
Server Crash [1.12.2]

### ISSUE THREAD

**Issue by HeberonYT** [mcpecommander/Mobultion-mod#7]
Hello
I was exploring my world and suddenly the server where I play fell. Now every time I enter it closes and I can not continue.
here is the error report.
regards!

Minecraft: 1.12.2
Mod: mobultion-0.2.jar
forge-1.12.2-14.23.2.2624

CrashReport:
https://pastebin.com/raw/v4hzQsDn

**Comment by mcpecommander** [comment]
I am sorry this happened, I did not test that part quite enough and I am not releasing any current updates due to school so you will have to wait till mid-April at least.

**Comment by mcpecommander** [comment]
It was fixed in the upcoming 0.3 released on Sunday 22/4
