### ISSUE TITLE
Ticking Entity Crash

### ISSUE THREAD

**Issue by ghost** [mcpecommander/Mobultion-mod#8]
Apparently a Zombie from your mod caused this?

Was running fine for a good week or two, until this happened.

https://pastebin.com/8CV9RLeL

**Comment by mcpecommander** [comment]
That is a big known issue with some animations overlapping and the api did not update to protect against it and I am not releasing any updates due to schools so you will have to excuse me until May or mid-April.

**Comment by mcpecommander** [comment]
Maybe fixed, I will keep an eye on it since the api has not yet updated.
